#
name: Netlify.io Frontend deployment

# integration berjalan ketika apa
on:
  push:
    branches:
      - master
      - Challenge_8
jobs:
  deploy:
    name: deploy frontend using netlify
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./Frontend"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: Deploy to Netlify
        run: netlify deploy --prod
#      - name: deployment with netlify
#        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: "./Frontend/build"
          comment-on-commit: true
